import 'package:uuid/uuid.dart';
import 'priority.dart';
import 'recurrence.dart';
import 'task.dart';

/// Represents a structured reminder suggestion generated by the AI assistant before confirmation.
class AiReminderDraft {
  final String title;
  final String description;
  final DateTime dueDate;
  final int dueHour;
  final int dueMinute;
  final Priority priority;
  final Recurrence recurrence;
  final String? url;
  final List<String> channels;
  final String? reasoning;
  final String rawPrompt;

  const AiReminderDraft({
    required this.title,
    this.description = '',
    required this.dueDate,
    required this.dueHour,
    required this.dueMinute,
    this.priority = Priority.medium,
    this.recurrence = Recurrence.none,
    this.url,
    this.channels = const ['local', 'whatsapp'],
    this.reasoning,
    required this.rawPrompt,
  });

  /// Bridges this AI draft into an immutable [Task] ready for persistence and notification scheduling.
  Task toTask({String? id, DateTime? createdAt}) {
    return Task(
      id: id ?? const Uuid().v4(),
      title: title,
      description: description,
      dueDate: dueDate,
      dueHour: dueHour,
      dueMinute: dueMinute,
      priority: priority,
      recurrence: recurrence,
      url: url,
      channels: channels,
      isNotificationEnabled: true,
      isCompleted: false,
      createdAt: createdAt ?? DateTime.now(),
    );
  }

  /// Returns a copy of this draft with the given fields replaced.
  AiReminderDraft copyWith({
    String? title,
    String? description,
    DateTime? dueDate,
    int? dueHour,
    int? dueMinute,
    Priority? priority,
    Recurrence? recurrence,
    String? url,
    List<String>? channels,
    String? reasoning,
    String? rawPrompt,
  }) {
    return AiReminderDraft(
      title: title ?? this.title,
      description: description ?? this.description,
      dueDate: dueDate ?? this.dueDate,
      dueHour: dueHour ?? this.dueHour,
      dueMinute: dueMinute ?? this.dueMinute,
      priority: priority ?? this.priority,
      recurrence: recurrence ?? this.recurrence,
      url: url ?? this.url,
      channels: channels ?? this.channels,
      reasoning: reasoning ?? this.reasoning,
      rawPrompt: rawPrompt ?? this.rawPrompt,
    );
  }

  Map<String, dynamic> toJson() => {
        'title': title,
        'description': description,
        'dueDate': dueDate.toIso8601String(),
        'dueHour': dueHour,
        'dueMinute': dueMinute,
        'priority': priority.name,
        'recurrence': recurrence.name,
        'url': url,
        'channels': channels,
        'reasoning': reasoning,
        'rawPrompt': rawPrompt,
      };

  factory AiReminderDraft.fromJson(Map<String, dynamic> json) {
    return AiReminderDraft(
      title: json['title'] as String? ?? '',
      description: json['description'] as String? ?? '',
      dueDate: DateTime.parse(json['dueDate'] as String),
      dueHour: json['dueHour'] as int? ?? 9,
      dueMinute: json['dueMinute'] as int? ?? 0,
      priority: Priority.fromString(json['priority'] as String?),
      recurrence: Recurrence.fromString(json['recurrence'] as String?),
      url: json['url'] as String?,
      channels: json['channels'] != null
          ? List<String>.from(json['channels'] as List)
          : const ['local', 'whatsapp'],
      reasoning: json['reasoning'] as String?,
      rawPrompt: json['rawPrompt'] as String? ?? '',
    );
  }
}
